_base_:
  - cfgs/train/dataset/base_dataset.yaml
  - cfgs/train/train_base.yaml
  - cfgs/train/tuning_base.yaml

train:
  save_step: 100
  train_steps: 10000

  scheduler:
    name: "one_cycle"
    num_warmup_steps: 500
    num_training_steps: ${train.train_steps}
    scheduler_kwargs: {} # args for scheduler

model:
  pretrained_model_name_or_path: "stabilityai/stable-diffusion-xl-base-1.0"
  tokenizer_repeats: 1
  ema_unet: 1
  ema_text_encoder: 1

unet:
  - lr: 1e-7
    layers:
      - "" # fine-tuning all layers in unet

## fine-tuning text-encoder
text_encoder:
  - lr: 1e-7
    layers:
      - ""

data_cfg:
  batch_size: 30
  img_root: "data/imgs"  # img path
  caption_file: "data/tags/" # caption path
  target_area: 424*424 # expected resolution

# The dataset configuration inherits base_dataset.yaml

data:
  dataset1:
    batch_size: ${data_cfg.batch_size}
    cache_latents: True
    
    source:
      data_source1:
        img_root: ${data_cfg.img_root}
        prompt_template: "prompt_tuning_template/galaxy.txt"
        caption_file: ${data_cfg.caption_file}

    bucket:
      _target_: hcpdiff.data.bucket.SizeBucket.from_files # aspect ratio bucket
      target_area: ---
      num_bucket: 1
